version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: homework
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
  app:
    image: hungquach:lastest
    restart: always
    environment:
      CONNECTION_STRING: "postgres://admin:admin@db:5432/homework"
    build:
      context: .
      dockerfile: dockerfile
    ports: 
      - 3000:3000
    depends_on: 
      - db

volumes:
  postgresql:
  postgresql_data: